# 95% stolen from the example...
image: hirokimatsumoto/alpine-openjdk-11

before_script:
  - java -version
  - javac -version
  # Install SBT
  # - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  # - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  - apk update -y
  - apk add sbt -y
  - sbt sbt-version

test:
  script:
    - bash ci.sh
